### PR TITLE
Ensure MC slaves are set to ready after timeouts

### PR DESCRIPTION
**Pull request by irowebbn**
Addresses part 1 of #1369

### CODE REVIEW

**Comment by irowebbn** [comment]
I'm not entirely sure why the macOS test failed. Skimming the logs, it doesn't seem related to my change, but the check was passing before, so...

**Comment by jdeans289** [comment]
Hi Isaac, thank you for your contribution! It looks like the MacOS pipeline has a dependency issue right now, some of our other pull requests are failing with the same error. We're going to look into that on our side first, then we'll see about getting this merged.

**Comment by spfennell** [comment]
Hi @irowebbn, the pipeline has been fixed. Please fast-forward your fork by merging in our master branch to re-run the macOS CI. Thank you!

@spfennell

**Comment by irowebbn** [comment]
Looks like all the checks passed. Is there anything more needed to get merged?

**Pull request merged**
