### PR TITLE
Robustify YAML config file validation

### PR DESCRIPTION
**Pull request by ddj116**
* Fixed run path/too/deep duplication logic
* Add more unit testing to cover edge cases in the YAML file
* Unify type checking to reduce code duplication
* Empty sections like run: are still ignored but now produce an error
  to remind the user to clean them up.

Refs #1159

### CODE REVIEW

**Comment by spfennell** [comment]
@ddj116 Is this still a draft or is it ready for review?

**Comment by spfennell** [comment]
@ddj116 No worries, there is no urgency, you can leave this PR here as long as you like. I was just curious.

**Comment by ddj116** [comment]
OK @spfennell -- I believe this is ready to go whenever you are.

**Comment by ddj116** [comment]
Sorry on the false alarm on being ready, I found a few more enhancements I'd like to work before merging this.  Will take out of draft when ready for reals lol.

**Comment by ddj116** [comment]
OK improvements made and complete. Ready to merge pending successful Actions @spfennell

**Comment by ddj116** [comment]
Per discussion with Scott, I'm allowed to merge content without approval as long as it's TrickOps only. 

Merging! 🥳

**Pull request merged**
