### PR TITLE
Print a stack trace when exec_terminate is called

### LINKED ISSUE #635: Print a stack trace when exec_terminate is called
So you can point the finger at the culprit!

### PR DESCRIPTION
**Pull request by dbankieris**
Closes #635

### CODE REVIEW

**Comment by iamthad** [comment]
Any reason to use this new backtrace code rather than just shelling out to `gdb` like the signal handlers do?

**Comment by dbankieris** [comment]
`exec_terminate` is the normal path by which a sim ends, so we don't want to always invoke gdb. Although you could break on the function yourself in gdb, that wasn't an option for the requester of this feature. He wanted an alternative method to identify the called of `exec_terminate`.

**Comment by alexlin0** [comment]
I don't think this is a capability we need.   The user should send exec_terminate a useful message indicating the reason for termination rather than asking Trick to provide a stack trace on exit.  

The old backwards compatible <code>exec_terminate(const char *file_name, const char *error) </code> doesn't include the line number where the call is made, the newer <code>exec_terminate_with_return(int ret_code, const char *file_name, int line, const char *error)</code> provides a field for the line number.

**Comment by dbankieris** [comment]
Only squeaky wheels get attention around here.

**Pull request closed without merging**
