### PR TITLE
Remove double include of S_overrides.mk

### PR DESCRIPTION
**Pull request by dbankieris**
I'm applying what I've learned in EG2: proper git workflow!

Refs #360

### CODE REVIEW

**Comment by dbankieris** [comment]
Look! We can even rebase and merge the pull request when we accept it so we don't get any ugly merge commits!

**Comment by dbankieris** [comment]
@alexlin0 NExSyS' SIM_mmsev and SIM_rover, IDF's sims, and Trick's sims all build under these changes,  so if you don't think the issue noted at the bottom of #360 is a big deal, it's merge time!

**Comment by alexlin0** [comment]
go ahead and merge it.

**Comment by alexlin0** [comment]
but I dispute that this is the only "proper git workflow".

**Comment by dbankieris** [comment]
I knew I could count on you, The Rash.

**Comment by dbankieris** [comment]
Well, that was easy.

**Comment by dbankieris** [comment]
@excaliburtb This will probably require a change to Pong's various `S_overrides.mk` files.

**Pull request merged**
