### PR TITLE
modified Java display for SIM_wheelbot so when RUN_mouse is used, ima…

### PR DESCRIPTION
**Pull request by Andyj4586**
…ges of waypoints stop being drawn when mouse arrives at waypoint. This is a minor change, just makes it seem like the mouse is eating the snacks. This is already in the process of being merged into TrickHLA, but thought it might be good to include in the trick repo.

### CODE REVIEW

**Comment by jdeans289** [comment]
This is cute!

It appears that you've added a space to the beginning of every line in the file, which confuses the git blame. We use this tool frequently in our development. Could you remove the space at the beginning of every line so git can clearly recognize what changes you made and what was pre-existing?

Don't worry about the failing test runs, those are due to a broken dependency upstream. We're fixing that internally.

Once you make this change we'll get this merged in. Thank you for your contribution!

**Comment by Andyj4586** [comment]
Just pushed again with all those extra spaces removed. I hope that solved the issue!

Thank you,
Andrew Young
________________________________

**Comment by jdeans289** [comment]
This looks great! We're going to hold off on merging this until we fix our CI runners; feel free to poke me if it's been awhile.

Thanks for your contribution!

**Comment by Andyj4586** [comment]
> Can you merge or rebase onto the current updated master?

Hi, sorry I was out of town for 2 weeks. I thought this pull request was to merge into the master? Do I need to do something locally on my end to merge in my repo? Apologies for the confusion, I'm still fairly new with git.

**Pull request merged**
