### PR TITLE
15.2.0

### PR DESCRIPTION
**Pull request by urroner**
I hope this is the right place to do this

I have gone over the tutorial and have located some problems with it.  This is from Sections 1 - 7.  Some of them are minor.  The problems are explained in the attached file.
[Trick_Tutorial_Problems-1.pdf](https://github.com/nasa/trick/files/202635/Trick_Tutorial_Problems-1.pdf)

### CODE REVIEW

**Comment by lordmundi** [comment]
Well I, for one, really love when people take the time to write all this
stuff up.  I'm sure the Trick developers feel the same way.  Thanks
@urroner !

**Comment by alexlin0** [comment]
@urroner : Thank you for the submission. This isn't the right place though.  Can you create an issue and attach your pdf?  If you have trouble I can do it, I just wanted to keep you as the original author.

**Comment by urroner** [comment]
Sorry about that.  I’ve created an issue.

**Comment by alexlin0** [comment]
I see the new issue, I am closing this pull request.

**Pull request closed without merging**
