### PR TITLE
Added separate_thread_set_enabled(bool) function to MessageSimObject class

### PR DESCRIPTION
**Pull request by hchen99**
For user to use the feature of letting trick to write the messages out on a separate thread in a more intuitive way (hopefully ;-).
Named the function as separate_thread_set_enabled(bool on_off) to match some other function naming convention. Feel free to let me know if a different function name is preferred.

### CODE REVIEW

**Review by jdeans289 — CHANGES_REQUESTED** [review]
Hi Hong, this looks great! Can you add documentation for this as well? Probably in 
`docs/documentation/simulation_capabilities/Status-Message-System.md`

**Comment by hchen99** [comment]
> Hi Hong, this looks great! Can you add documentation for this as well? Probably in `docs/documentation/simulation_capabilities/Status-Message-System.md`

Thanks! Sure, will do

**Comment by jdeans289** [comment]
I think there's a conflict now from the Variable server change, could you resolve that?

**Comment by hchen99** [comment]
> I think there's a conflict now from the Variable server change, could you resolve that?

I believe it is now resolved ;-)

**Review by jdeans289 — APPROVED** [review]

**Review by jmpenn — APPROVED** [review]
It looks good to me.

**Pull request merged**
